-- SPICE GARDEN - Supabase PostgreSQL database
-- Converted from the supplied MySQL SQL.
-- Run this entire script in Supabase SQL Editor.

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;

DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS order_type_enum CASCADE;
DROP TYPE IF EXISTS food_type_enum CASCADE;
DROP TYPE IF EXISTS user_role_enum CASCADE;

CREATE TYPE order_status AS ENUM ('Pending','Accepted','Preparing','Ready','Completed','Cancelled');
CREATE TYPE order_type_enum AS ENUM ('dine-in','takeaway');
CREATE TYPE food_type_enum AS ENUM ('veg','non-veg');
CREATE TYPE user_role_enum AS ENUM ('admin','staff');

CREATE TABLE restaurants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  logo_url VARCHAR(500),
  cover_image_url VARCHAR(500),
  description TEXT,
  address VARCHAR(500),
  phone VARCHAR(30),
  whatsapp_number VARCHAR(30) NOT NULL,
  google_maps_url VARCHAR(500),
  instagram_url VARCHAR(500),
  opening_time TIME,
  closing_time TIME,
  currency VARCHAR(10) DEFAULT 'INR',
  tax_percentage NUMERIC(5,2) DEFAULT 0,
  packaging_charge NUMERIC(10,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(30),
  role user_role_enum NOT NULL DEFAULT 'staff',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  display_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (restaurant_id, name)
);

CREATE TABLE menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  image_url VARCHAR(500),
  food_type food_type_enum NOT NULL DEFAULT 'veg',
  is_bestseller BOOLEAN NOT NULL DEFAULT FALSE,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  order_number VARCHAR(40) NOT NULL UNIQUE,
  customer_name VARCHAR(150) NOT NULL,
  customer_phone VARCHAR(30) NOT NULL,
  order_type order_type_enum NOT NULL,
  table_number VARCHAR(30),
  pickup_time TIMESTAMPTZ NULL,
  special_instructions TEXT,
  subtotal NUMERIC(10,2) NOT NULL,
  tax NUMERIC(10,2) NOT NULL DEFAULT 0,
  packaging_charge NUMERIC(10,2) NOT NULL DEFAULT 0,
  total NUMERIC(10,2) NOT NULL,
  status order_status NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id BIGINT REFERENCES menu_items(id) ON DELETE SET NULL,
  item_name VARCHAR(150) NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10,2) NOT NULL,
  special_instructions TEXT,
  subtotal NUMERIC(10,2) NOT NULL
);

-- Restaurant
INSERT INTO restaurants
(name,description,address,phone,whatsapp_number,opening_time,closing_time,currency,tax_percentage,packaging_charge)
VALUES
('SPICE GARDEN','Premium restaurant digital menu with WhatsApp ordering.','123 Food Street, Chennai, Tamil Nadu','+91 9876543210','9994521119','11:00:00','23:00:00','INR',0,0);

-- Admin user.
-- IMPORTANT: this is a bcrypt hash for the password Admin@123.
-- If your backend uses bcrypt.compare(), this will work.
INSERT INTO users
(restaurant_id,full_name,email,password_hash,phone,role)
VALUES
((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),
 'SPICE GARDEN Admin','admin@spicegarden.com',
 '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
 '9876543210','admin');


INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Biryani',1);;
INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Main Course',2);;
INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Starters',3);;
INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Rice',4);;
INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Chinese',5);;
INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Beverages',6);;
INSERT INTO categories (restaurant_id,name,display_order) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),'Desserts',7);;

INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Biryani'),'Chicken Biryani','Aromatic basmati rice layered with tender chicken and traditional biryani spices.',220,'https://154630363.cdn6.editmysite.com/uploads/1/5/4/6/154630363/T2HYUZFGIYTWIX65Q3A63OSE.png?optimize=medium&width=2400','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Biryani'),'Mutton Biryani','Fragrant basmati rice slow-cooked with tender mutton and aromatic spices.',280,'https://dineout-media-assets.swiggy.com/swiggy/image/upload/fl_lossy%2Cf_auto%2Cq_auto%2Cw_600%2Ch_468/DINEOUT_ALL_RESTAURANTS/IMAGES/RESTAURANT_IMAGE_SERVICE/2025/2/24/990d2b9f-bd06-4975-9353-8716afe3f7e8_image74857fef7ab394489b12f0ec036977f16.JPG','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Biryani'),'Egg Biryani','Spiced basmati rice served with seasoned boiled eggs.',190,'https://akash.net.np/uploads/restaurant/food-items-biryani-egg-biryani.jpeg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Biryani'),'Veg Biryani','Long-grain basmati rice cooked with seasonal vegetables and biryani spices.',180,'https://tb-static.uber.com/prod/image-proc/processed_images/2cf3b8f2e83b2852c4d3b6f33328abcd/c67fc65e9b4e16a553eb7574fba090f1.jpeg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Biryani'),'Prawn Biryani','Aromatic biryani rice cooked with juicy prawns, herbs and spices.',300,'https://hungryforever.net/wp-content/uploads/2017/11/hyderabadi-prawn-biryani-recipe.jpg','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Butter Chicken','Tender chicken in a creamy tomato-butter gravy.',240,'https://b.zmtcdn.com/data/pictures/chains/8/19420268/5273fe3967e103160d1a3a507f2d4e86.jpg','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Chicken Curry','Tender chicken simmered in a rich, aromatic Indian curry.',220,'https://media-assets.swiggy.com/swiggy/image/upload/f_auto%2Cq_auto%2Cfl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2024/7/16/d8144ccf-6b13-415f-b4d5-1c898e2f4483_926598.jpg','non-veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Mutton Curry','Slow-cooked mutton pieces in a rich spiced gravy.',290,'https://snapcalorie-webflow-website.s3.us-east-2.amazonaws.com/media/food_pics_v2/medium/homemade_mutton_curry.jpg','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Paneer Butter Masala','Soft paneer in a creamy tomato and butter gravy.',200,'https://commons.wikimedia.org/wiki/Special:Redirect/file/Paneer_Butter_Masala.jpg','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Kadai Paneer','Paneer and peppers cooked with freshly ground kadai spices.',210,'https://www.cookwithmanali.com/wp-content/uploads/2017/03/Restaurant-Style-Kadai-Paneer-Recipe.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Dal Tadka','Creamy lentils finished with a sizzling ghee tempering.',150,'https://feastwithsafiya.com/wp-content/uploads/2021/10/dal-tadka.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Main Course'),'Mixed Vegetable Curry','Seasonal vegetables simmered in a flavorful Indian curry.',170,'https://snapcalorie-webflow-website.s3.us-east-2.amazonaws.com/media/food_pics_v2/medium/mix_vegetable_curry.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'Chicken 65','Crispy South Indian fried chicken tossed with curry leaves and chillies.',180,'https://opt.toiimg.com/recuperator/img/toi/m-60425530/60425530.jpg%26width%3D500%26resizemode%3D4','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'Chicken Tikka','Char-grilled chicken pieces marinated in yogurt and Indian spices.',220,'https://imageproxy.wolt.com/menu/menu-images/6151b54c5bed118046582db7/fb141206-1f93-11ec-885a-1648a60b56bc_chicken_tikka.jpeg','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'Chicken Manchurian','Crispy chicken coated in a glossy Indo-Chinese Manchurian sauce.',210,'https://www.chilitochoc.com/wp-content/uploads/2024/11/serving-spoon-in-manchurian-gravy.jpg','non-veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'Chilli Chicken','Crispy chicken tossed with peppers, onions and a spicy chilli sauce.',210,'https://cf-img-a-in.tosshub.com/sites/visualstory/stories/2022_10/story_11140/assets/2.jpeg?time=1664626819','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'Paneer Tikka','Charred paneer cubes with peppers and onions.',190,'https://miro.medium.com/v2/resize%3Afit%3A1024/1%2AkJpCB1zsTDZELlv7IvhaWg.png','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'Gobi 65','Crispy spiced cauliflower inspired by the classic Chicken 65.',150,'https://hospitalitycareerprofile.com/uploads/images/202605/image_1200x_6a06f3b411f84.webp','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Starters'),'French Fries','Golden crispy fries served with tomato ketchup.',110,'https://bizweb.dktcdn.net/thumb/grande/100/400/734/products/bi-quyet-chien-khoai-tay-thom-ngon-gion-rum-an-hoai-khong-chan-6-1f27760ca1fc4dafb511cc9c56995f86.jpg?v=1615878935283','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Rice'),'Steamed Rice','Fluffy steamed white rice.',90,'https://barona.vn/storage/meo-vat/198/1-chen-com-bao-nhieu-calo.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Rice'),'Jeera Rice','Basmati rice tempered with cumin and fresh herbs.',120,'https://www.cookingcarnival.com/wp-content/uploads/2021/06/Jeera-rice-2.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Rice'),'Ghee Rice','Fragrant rice tossed with ghee, whole spices, onions and cashews.',140,'https://cdn.tarladalal.com/media/Ghee%20Rice.webp','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Rice'),'Egg Fried Rice','Wok-tossed rice with scrambled egg and spring onions.',160,'https://yummygusto.com/assets/images/1738622731747-wdw9er60.webp','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Rice'),'Chicken Fried Rice','Wok-tossed rice with tender chicken and vegetables.',190,'https://commons.wikimedia.org/wiki/Special:FilePath/Chicken%20fried%20rice.jpg','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Rice'),'Veg Fried Rice','Wok-tossed rice with colorful vegetables and spring onions.',150,'https://image.cdn.shpy.in/299322/SKU-0156_0-1723623360567.jpg?format=webp','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Chinese'),'Veg Noodles','Hakka noodles tossed with fresh vegetables and sauces.',150,'https://www.sharmispassions.com/wp-content/uploads/2012/09/HakkaNoodles4-e1689045142580-720x720.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Chinese'),'Chicken Noodles','Hakka noodles tossed with chicken, vegetables and sauces.',190,'https://images.deliveryhero.io/image/fd-pk/LH/hhsf-hero.jpg?height=384&quality=45&width=512','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Chinese'),'Schezwan Fried Rice','Spicy Indo-Chinese fried rice with vegetables and Schezwan sauce.',170,'https://imagedelivery.net/AXc7J92bhb6Cxi2EHCwslA/49d21b80-c29a-41bd-b743-7dab4a74a200/public','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Chinese'),'Chilli Chicken','Crispy chicken, peppers and onions in a spicy chilli sauce.',210,'https://cf-img-a-in.tosshub.com/sites/visualstory/stories/2022_10/story_11140/assets/2.jpeg?time=1664626819','non-veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Chinese'),'Chicken Manchurian','Crispy chicken coated in a savory Manchurian glaze.',210,'https://www.chilitochoc.com/wp-content/uploads/2024/11/serving-spoon-in-manchurian-gravy.jpg','non-veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Chinese'),'Gobi Manchurian','Crispy cauliflower florets tossed in a glossy Manchurian sauce.',160,'https://images.squarespace-cdn.com/content/v1/5c340a92365f022709793b71/1619453186921-O7FXHCQV0KRBSO60KT0D/gobimanchurian.jpeg?format=1000w','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Fresh Lime Soda','Chilled soda with fresh lime, ice and mint.',80,'https://jaiindiankitchen.com/media/products/fresh-lime-soda-jai-indian-kitchen.jpeg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Tea','Freshly brewed Indian masala tea.',50,'https://b.zmtcdn.com/data/pictures/3/19250623/a8becd5dfeed39fb16d5eb6dd555947c.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Coffee','Traditional South Indian filter coffee.',70,'https://www.cookwithmanali.com/wp-content/uploads/2022/03/South-Indian-Filter-Coffee-676x1024.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Milkshake','Creamy chilled milkshake topped with a light garnish.',140,'https://media-assets.swiggy.com/swiggy/image/upload/f_auto%2Cq_auto%2Cfl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2025/12/11/535fccb2-f390-4a35-840d-008a03acb26e_1284915.jpg','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Mineral Water','Chilled packaged drinking water.',30,'https://cdn.mafrservices.com/sys-master-root/hde/h96/63491771531294/666718_main.jpg?im=Resize%3D480','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Desserts'),'Gulab Jamun','Soft milk-solid dumplings soaked in fragrant sugar syrup.',90,'https://menafn.com/updates/pr/2024-03/19/AN_f6408401-b_Image_In_Body.jpg','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Desserts'),'Ice Cream','Creamy chilled ice cream; ask for today''s available flavor.',100,'https://m.media-amazon.com/images/I/71APXXCsz5L._UF894%2C1000_QL80_.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Desserts'),'Brownie','Rich, fudgy chocolate brownie served warm.',130,'https://loremflickr.com/900/700/chocolate-brownie?lock=41','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Desserts'),'Fruit Salad','Fresh seasonal fruits served chilled.',120,'https://www.cuisini-blog.de/wp-content/uploads/2023/01/obstsalat-rezept-4-1280x853.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Desserts'),'Carrot Halwa','Slow-cooked grated carrots with milk, ghee, sugar and nuts.',120,'https://res.cloudinary.com/jerrick/image/upload/d_642250b563292b35f27461a7.png%2Cf_jpg%2Cfl_progressive%2Cq_auto%2Cw_1024/63f31af1998c83001dba03b9.jpg','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Desserts'),'Falooda','Layered chilled dessert drink with vermicelli, basil seeds and ice cream.',160,'https://amritsarfoods.com/cdn/shop/files/rosefalooda.jpg?v=1725258887','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Lemon Mint Juice','Refreshing lemon and mint juice served chilled with ice and a lemon garnish.',80,'https://snapcalorie-webflow-website.s3.us-east-2.amazonaws.com/media/food_pics_v2/medium/lemon_mint_juice.jpg','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Orange Juice','Freshly squeezed orange juice served chilled.',90,'https://commons.wikimedia.org/wiki/Special:Redirect/file/Orangejuice.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Watermelon Juice','Fresh watermelon juice served chilled.',90,'https://commons.wikimedia.org/wiki/Special:Redirect/file/Watermelon%20juice%20in%20a%20glass.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Pineapple Juice','Fresh pineapple juice served chilled.',90,'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pineapple%20juice.JPG','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Grape Juice','Fresh grape juice served chilled.',90,'https://s3-eu-west-1.amazonaws.com/elmenusv5-stg/Normal/6b24c01d-2b23-4fbd-a069-8f3171e9be18.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Mosambi Juice','Fresh sweet-lime juice served chilled.',90,'https://www.bbassets.com/media/uploads/p/xl/40233335_2-fresho-mosambi-juice.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Carrot Juice','Fresh carrot juice served chilled.',90,'https://commons.wikimedia.org/wiki/Special:Redirect/file/020240210%20carrot%20juice.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Mixed Fruit Juice','A refreshing blend of seasonal fruits.',100,'https://loremflickr.com/900/700/mixed-fruit-juice?lock=308','veg',TRUE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Coca-Cola','Chilled Coca-Cola served cold.',60,'https://gadapizza.com/14-superlarge_default/coca-cola-330-ml.webp','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Pepsi','Chilled Pepsi served cold.',60,'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pepsi%20Can.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Sprite','Chilled Sprite served cold.',60,'https://decapote.com/398-large_default/sprite-lata-33-cl-pack-24-und.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'7UP','Chilled 7UP served cold.',60,'https://cdn.mafrservices.com/sys-master-root/hf0/hfe/17521377607710/153229_main.jpg?im=Resize%3D400','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Fanta','Chilled Fanta served cold.',60,'https://commons.wikimedia.org/wiki/Special:Redirect/file/Fanta%20Orange.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Mirinda','Chilled Mirinda served cold.',60,'https://commons.wikimedia.org/wiki/Special:Redirect/file/PEPSI%20MIRINDA%20ORANGE%20FLAVOR%20CHINA%20VERSION.jpg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Thums Up','Chilled Thums Up served cold.',60,'https://cdn.uengage.io/uploads/18085/image-314316-1687416275.jpeg','veg',FALSE,TRUE);;
INSERT INTO menu_items (restaurant_id,category_id,name,description,price,image_url,food_type,is_bestseller,is_available) VALUES ((SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1),(SELECT id FROM categories WHERE restaurant_id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1) AND name='Beverages'),'Mountain Dew','Chilled Mountain Dew served cold.',60,'https://amici.ph/cdn/shop/products/mountain-dew-can.jpg?v=1518899296','veg',FALSE,TRUE);;

-- Food-type corrections from the supplied SQL
UPDATE menu_items SET food_type='non-veg' WHERE id=3;
UPDATE menu_items SET food_type='non-veg' WHERE id=23;

-- Make sure the restaurant WhatsApp number is the requested number
UPDATE restaurants SET whatsapp_number='9994521119' WHERE id=(SELECT id FROM restaurants WHERE whatsapp_number='9994521119' LIMIT 1);

-- Helpful indexes for the admin dashboard and same-day active-order lookup
CREATE INDEX idx_orders_restaurant_created_at ON orders(restaurant_id, created_at);
CREATE INDEX idx_orders_customer_lookup ON orders(restaurant_id, customer_phone, customer_name, order_type, table_number, status, created_at);
CREATE INDEX idx_menu_items_restaurant_food_type ON menu_items(restaurant_id, food_type, is_available);

-- Auto-update updated_at timestamps
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER restaurants_updated_at BEFORE UPDATE ON restaurants FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER menu_items_updated_at BEFORE UPDATE ON menu_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();